### ISSUE TITLE
Need access to identify current Item

### ISSUE THREAD

**Issue by AjazDev** [JWAutumn/ACarousel#1]
@TheAuttom 
@JWAutumn 
It's an awesome library for this feature, First in SwiftUI I think. 
However there is an improvement that will make it more useful.

There is no way to access the information what object is currently in Focus. 
a) In case of Auto Scrolling turned ON 
b) In case of Auto Scrolling turned OFF and user is manually dragging etc. 

There is an AState Observable Object but it is set to private. Can you please provide a way to get that information?

**Comment by JWAutumn** [comment]
Thank you for your issue. I revised and updated [it](https://github.com/JWAutumn/ACarousel). Feel free to visit
