### ISSUE TITLE
ACarousel_LibraryContent 問題

### ISSUE THREAD

**Issue by Steven364** [JWAutumn/ACarousel#3]
參考你的程式中 發現到您撰寫了 ACarousel_LibraryContent
想請教這個的用途是？？

**Comment by JWAutumn** [comment]
> 參考你的程式中 發現到您撰寫了 ACarousel_LibraryContent
> 想請教這個的用途是？？

可以参考一下我写的这篇文章： [SwiftUI 把自定义的 View 和 Modifier 添加到 Xcode Library 中](https://juejin.cn/post/6896735430315868167)
